version: "3"
services:
  app:
    build: .
    environment:
      INSERTION_QUEUE: insertion.queue
      VALIDATION_QUEUE: validation.queue
      NUMBER_OF_VALIDATION_CONSUMERS: 1
      RESPONSE_EXCHANGE: response.exchange
      RESPONSE_ROUTING_KEY: response.routing.key
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_VHOST: /
      RABBITMQ_USERNAME: guest
      RABBITMQ_PASSWORD: guest
      JDBC_URL: jdbc:mysql://mysql:3306/axr_challenge?user=root&password=secret
    depends_on:
      - mysql
      - rabbitmq
    ports:
      - 8080:8080
  mysql:
    image: mysql:5.7
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: axr_challenge
      MYSQL_USER: rootu
      MYSQL_PASSWORD: rootp
  rabbitmq:
    image: rabbitmq:3.6-management
    ports:
    - 15672:15672
